#!/usr/bin/env python3
import faker

fk = faker.Faker(locale='zh-cn')
print('faker函数：')
print(fk.__dir__())

print('名字：',fk.name())
print('姓氏：',fk.last_name(),fk.first_name())
print('电话号码:',fk.phone_number())
print('地址：',fk.address())
print('街道地址:',fk.street_address())
print('街道名：',fk.street_name())
print('国家：',fk.country())
print('区:',fk.district())
print('地理坐标：',fk.geo_coordinate())
print('随机数:',fk.numerify())
print('省份：',fk.province())
print('随机颜色:',fk.color_name())
print('随机公司服务名:',fk.color_name())
print('随机公司名：',fk.company())
print('随机日期:',fk.date())
print('随机邮件:',fk.email())
print('随机域名:',fk.free_email_domain())
print('安全邮箱：',fk.safe_email())
print('IP地址:',fk.ipv4())
print('mac地址:',fk.mac_address())
print('随机话:',fk.sentence())
print('随机文章：',fk.text())
print('男姓名:',fk.name_female())
print('女姓名:',fk.name_male())
#print('随机档案:',fk.profile())
print('身份证信息：',fk.ssn())
print('浏览器：',fk.chrome())
